name: ProtectPlugin
version: 0.3.0-SNAPSHOT
main: com.mengcraft.protect.Protect

commands:
  protect:
    description: Admin command for this.
    permission: server.admin
    
permissions:
  server.admin:
     description: Admin permission for this.
     default: op